version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.9-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/currency

    steps:
      - checkout
      - restore_cache:
          key: mcs-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: cd ~/currency && npm install
      - save_cache:
          key: mcs-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
             - "node_modules"
      - run: cd ~/currency && npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI